# Generated by Django 3.2.3 on 2022-04-21 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='myimages')),
                ('category', models.CharField(choices=[('Gentleman', 'Gentleman'), ('Ladies', 'Ladies'), ('Children', 'Children'), ('Necklace', 'Necklace'), ('Bracelets', 'Bracelets'), ('Ring', 'Ring'), ('Earrings', 'Earrings'), ('Bags', 'Bags'), ('Glasses', 'Glasses'), ('Shoes', 'Shoes'), ('Hats', 'Hats')], max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('yellow', 'yellow'), ('red', 'red'), ('orange', 'orange'), ('pink', 'pink'), ('violet', 'violet'), ('green', 'green'), ('blue', 'blue'), ('Sky blue', 'Sky blue'), ('beige', 'beige'), ('brown', 'brown'), ('Silver', 'Silver')], max_length=20, null=True)),
                ('size', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50, null=True)),
                ('Lastname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('DOB', models.DateField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=2)),
                ('comment', models.CharField(max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('coupon', models.CharField(max_length=20)),
                ('payment', models.CharField(choices=[('Promptpay', 'Promptpay'), ('credit/debit', 'credit/debit')], default='Promptpay', max_length=30)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.profile')),
            ],
        ),
    ]
