# Generated by Django 3.2.3 on 2022-04-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220421_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black'), ('yellow', 'yellow'), ('red', 'red'), ('orange', 'orange'), ('pink', 'pink'), ('violet', 'violet'), ('green', 'green'), ('blue', 'blue'), ('Sky blue', 'Sky blue'), ('beige', 'beige'), ('brown', 'brown'), ('grey', 'grey'), ('silver', 'silver'), ('golden', 'golden')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
